title: Gerard Gallen
description: Senior Technical Writer, Documentation Strategist, and Information Architect
author: Gerard Gallen
remote_theme: just-the-docs/just-the-docs

url: "https://gerryg2583.github.io"
baseurl: "/gerardgallen.github.io"

search_enabled: true
color_scheme: light
